project:
  type: book

book:
  title: "The Transmutation Spellbook"
  author: "Saruman, Dungeon Master"
  date: "10/21/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - joy.ipynb
    - part: Homework
      chapters:
        - hw03.ipynb
        - hw04.ipynb
        - hw05.ipynb
        - hw06.ipynb
        - hw07.ipynb
        - hw08.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
 # pdf:
  #  documentclass: scrreprt



